#Site Settings
title: "OVRDC GIS Tutorials"
email: mmeyer@ovrdc.org
description: "This site contains a series of web map tutorials and examples. It focuses on simple examples with the full code below the map. This site includes examples from Leaflet, Turf JS and Mapbox GL JS."
twitter_username: getbounds
github_username:  ovrdc
img: site-feature-image.png
author: Malcolm Meyer

#source files
layouts_dir:  _jekyll/_layouts
includes_dir: _jekyll/_includes

# Build settings
baseurl: /gis-tutorials
url: https://ovrdc.github.io
exclude: ["programs", "dev", "FirefoxPortable.exe","GeanyPortable.exe", "*.mxd"]
markdown: kramdown
highlighter: rouge
permalink: /:title/
sass:
    style: compressed

collections:
  leaflet:
    output: true
    about: >-
      A basic introduction to the Leaflet Web Mapping API. The examples cover adding data, styling and basic interaction. We also cover creating a choropleth map and doing basic GIS analysis in the browser with TurfJS.
    authors:
      - OVRDC | Malcolm Meyer
      - Prime 3sg | Jon Woyame & Jesse Glascock

  mapbox:
    output: true
    about: >-
      An introduction to the Mapbox GL JS API. The examples cover data adding data, data-driven styling, polygon extrusion and more. This set of tutorials was created for a workshop at the 2017 <a href="http://ogrip.oit.ohio.gov/Events/OhioGISConference.aspx" target="_blank">Ohio GIS Conference</a>. More roboust examples can be found on the <a href="https://www.mapbox.com/mapbox-gl-js/examples/" target="_blank">Mapbox</a> website.
    authors:
      - OVRDC | Malcolm Meyer

defaults:
  - scope:
      path: ""
      type: leaflet
    values:
      layout: leaflet
  - scope:
      path: ""
      type: mapbox
    values:
      layout: mapbox
