#Site Settings
title: "OVRDC GIS Tutorials"
email: mmeyer@ovrdc.org
description: "This site contains a series of web map tutorials and examples."
twitter_username: getbounds
github_username:  ovrdc

# Build settings
baseurl: /gis-tutorials
url: https://ovrdc.github.io
exclude: ["programs", "dev", "FirefoxPortable.exe","GeanyPortable.exe", "*.mxd"]
markdown: kramdown
highlighter: rouge
permalink: /:title/index.html

collections:
  leaflet:
    output: true
    about: >-
      A basic introduction to the Leaflet Web Mapping API. The examples cover adding data, styling and basic interaction. We also cover creating a choropleth map and doing basic GIS analysis in the browser with Turf.
    authors:
      - OVRDC | Malcolm Meyer
      - Prime 3sg | 

defaults:
  - scope:
      path: ""
      type: leaflet
    values:
      layout: leaflet
